### ISSUE TITLE
Code Review of Tweet Generator Submission 2

### ISSUE THREAD

**Issue by SWHarrison** [sprajjwal/CS-1.2-Intro-Data-Structures#2]
- All tests pass with no errors, great job!
- Great job implementing stretch challenges! I would recommend trying the iterable challenge. It will be helpful later on.
- Your ```find``` method does not return None when no match is found. While python does this automatically, it Is good practice to be as explicit as possible!

**Comment by sprajjwal** [comment]
I am pretty sure my linkedlist returns None, when not found. You sure it doesn't?
