### ISSUE TITLE
Hashtable Submission

### ISSUE THREAD

**Issue by Sukhrobjon** [sprajjwal/CS-1.2-Intro-Data-Structures#3]
- Please don't forget to annotate the time complexities, it helps you understand the concepts more.
- You don't need to use `node` in this line `node = bucket.find(lambda k: k[0] == key)` as `bucket.find()` the function returns an item, not a node. Also, you can just pass the `node` into the `delete()` method. Since it the `delete()` method you are calling from `linkedlist.py` file takes only 1 argument which is an item
- Don't forget to remove the old code from the starter code (Alan provided), since you have done all `TODOs`.

**Comment by sprajjwal** [comment]
- Fixed the time complexities.
- I think i should have called nodes, data or tuple since thats what they were. I updated it to be called data.
- TODOs removed.

Thanks! :D
